# Generated by Django 5.2 on 2025-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('bookDescription', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=255)),
                ('pageCount', models.IntegerField()),
                ('borrowPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('Science', 'science'), ('Novel', 'novel'), ('Poetry', 'poetry'), ('mystery', 'Mystery'), ('Comedy', 'comedy'), ('fantasy', 'Fantasy'), ('Horror', 'horror')], max_length=50)),
                ('image', models.ImageField(upload_to='book-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user-images/')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=10)),
            ],
        ),
    ]
