# Generated by Django 5.2 on 2025-05-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('science', 'Science'), ('novel', 'Novel'), ('poetry', 'Poetry'), ('mystery', 'Mystery'), ('Comedy', 'comedy'), ('Fantasy', 'fantasy'), ('horror', 'Horror')], max_length=50),
        ),
    ]
