# Generated by Django 5.2 on 2025-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_member_members_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('science', 'Science'), ('Novel', 'novel'), ('poetry', 'Poetry'), ('Mystery', 'mystery'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('Horror', 'horror')], max_length=50),
        ),
    ]
