# Generated by Django 5.2 on 2025-05-13 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_favouritebooks_ownedbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritebooks',
            options={'verbose_name_plural': 'Favourite Books'},
        ),
        migrations.AddField(
            model_name='favouritebooks',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favouritebooks',
            unique_together={('member', 'book')},
        ),
    ]
