# Generated by Django 5.2 on 2025-05-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_books_count_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('Science', 'science'), ('novel', 'Novel'), ('poetry', 'Poetry'), ('mystery', 'Mystery'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('Horror', 'horror')], max_length=50),
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.members')),
            ],
        ),
    ]
