# Generated by Django 5.2 on 2025-05-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_favouritebooks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritebooks',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favouritebooks',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favouritebooks',
            name='date_added',
        ),
    ]
