# Generated by Django 5.2 on 2025-05-13 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_favouritebooks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbooks',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
