# Generated by Django 5.2 on 2025-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_books_category_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('science', 'Science'), ('novel', 'Novel'), ('Poetry', 'poetry'), ('mystery', 'Mystery'), ('Comedy', 'comedy'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], max_length=50),
        ),
    ]
