# Generated by Django 5.2 on 2025-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('Science', 'science'), ('Novel', 'novel'), ('Poetry', 'poetry'), ('mystery', 'Mystery'), ('Comedy', 'comedy'), ('fantasy', 'Fantasy'), ('Horror', 'horror')], max_length=50),
        ),
    ]
