# Generated by Django 5.2 on 2025-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ownedbooks_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
