# Generated by Django 5.2 on 2025-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_members_username_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('science', 'Science'), ('novel', 'Novel'), ('Poetry', 'poetry'), ('mystery', 'Mystery'), ('Comedy', 'comedy'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
