# Generated by Django 5.2 on 2025-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_books_category_alter_members_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('history', 'History'), ('romance', 'Romance'), ('science', 'Science'), ('novel', 'Novel'), ('poetry', 'Poetry'), ('Mystery', 'mystery'), ('Comedy', 'comedy'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
