# Generated by Django 5.2 on 2025-05-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_books_category_alter_books_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bookDescription',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
