# Generated by Django 5.2 on 2025-05-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_books_bookdescription_remove_books_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='language',
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='published',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='ratingCount',
            field=models.IntegerField(null=True),
        ),
    ]
